create table potential_client_requests
(
    id                  serial primary key,
    company_name        varchar(255),
    info_for_estimation text,
    date_of_request     date,
    date_of_answer      date,
    answer              text,
    notes               text
);


INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ООО «Лунда» (не участник выставки)', E'Запрос из Бавария, Кельхайм 93 куб в Москву, 90 куб газовые котлы', E'2020-02-26', E'2020-02-26', E'2700 евро', E'отказали');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Шмальц ООО', E'Glatten Германия Москва , краны , 93 куб', E'2020-02-26', E'2020-02-26', E'3000 евро', E'28,02,2020 У них свой перевозчик с которым сотрудничают много лет  Договор заключался в Германии и даже, если у них есть новые проекты они принципиально не меняют перевозчика');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ООО "ЭЛАСТОИМПЭКС"', E'собственник, 90 куб, сырьё, 21т., паллеты,  зад бок, Германия 49 кв, на месте,   Дмитровское шоссе, Смоленск', E'2020-02-27', E'2020-02-27', E'2500 евро', E'отправили КП в отдел логистики, но логист пояснил, что они якобы возят на 500 евро дешевле.');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Белорусская экспедиция с биржи Lardi', E'экспедитор, 30 кал по ориг , ТНП , 15т , палет ,бок верх ,Польша г.Цеханув 06 квадрат - То в РФ Смоленск- выгрузка Тольятти', E'2020-02-27', E'2020-02-27', E'2400 евро', E'они предлагали ставку 2000');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Константин', E'Москва-Бейрут авиа, медицинские маски, 30 кор по 10 кг, объем 50*40*30, оплатакак нам удобно, экспорт наш', E'2020-03-02', E'2020-03-03', E'130 000 рублей, включено: авиадоставка, экспортные формальности в аэропорту отправки. Не включено: приём/оформление в Бейруте- оформляется получателем.', E'контакт в whatsApp Константин медмаски  другие дали 1500 долларов. Но проблема в разрешении на вывоз');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('sunsystem-russia', E'Их условия: Шумэн Болгария - Москва 120 куб, оборудование для отопления и горячего водоснабжения, паллеты, таможня в европе на месте, в РФ рассматриваем наш таможенный пост их ставка 2700', E'2020-03-02', E'2020-03-03', E'2700евро - транзит через Украину 3600евро - транзит через РБ', E' Поставили нас в резерв, но вопрос о смене перевозчика подымать не собираются');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Формет Пластик Машинери ООО/ ООО "Пластмаш"', E'Германия 85 кв.- Дзержинск нижегородскаяобласть, паллеты, оборудование, растаможка Дзержинск', E'2020-03-03', E'2020-03-03', E'2900 евро , ставка на данный момент. Готовы обговорить предложение Клиента', E'Поставили нас в резерв');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ПромСнаб', E'Милан Питер 90 куб, упаковочное оборудование,, паллеты, таможня Литва,, растамаживаемся в Питере', E'2020-03-04', E'2020-03-04', E'Оформление в Италии- 3900евро  Оформление в Литве- 3500 евро при условии что сообщат о загрузке за 7 дней', E'юрий передал информацию кому то');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ПромСнаб', E'Китай Питер КП', E'2020-03-04', E'2020-04-03', E'ответ в файле', E'юрий передал информацию кому то');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Бестром ЗАО', E'Требуемый транспорт Авто / Авиа  2. Наименование груза Упаковочное оборудование, комплектующие, запчасти.  3. Вес 50 кг – 300 кг  4. Как упакован груз ? в коробках/ящиках на деревянных паллетах  5. Форма загрузки.  6. Адрес загрузки- название города или код и маршрут Eikendael 18, 2245 BL Wassenaar, The Netherlands  7. Место таможенного оформления в Европе  8. Адрес доставки РФ, МО, г. Красногорск, д. 15  9. Адрес таможенного прибытия. Истра-Терминал     • Азия     1. Страна, порт отправки, условия поставки FCA, DDU  2. Маршрут следования (порт перевалки, место доставки) NO.27 Caihong Road,Shiban,Lunjiao,Shunde,Foshan,Guangdong,China  -> РФ, МО, г. Красногорск, д. 15  3. Требуемый тип контейнера, вес груза 3-4 т  4. Желаемая стоимость доставки     • Америка    5. Порт отправки, условия поставки   6. Маршрут следования (порт перевалки, место доставки) 22А Bacton Hill Road Frаzet, Pennsylvania 19З55, USA -> РФ, МО, г. Красногорск, д. 15  7. Требуемый тип контейнера, вес груза 100 – 300 кг  8. Желаемая стоимость доставки', E'2020-03-04', E'2020-03-10', E'1. АВТО перевозка                                                                                                                                              2245 Нидерланды - таможня Истра: доставка до СВХ, 300кг, 1 паллета - 460 евро ( 9-13 дней)                                                                                                                                                        вывоз груза Истра- Красногорск - 9000 рублей                                                                                              2. море+ЖД в сборном контейнере  NO.27 Caihong Road,Shiban,Lunjiao,Shunde,Foshan,Guangdong,China- Владивосток - МО, г. Красногорск  Груз: оборудование 4 т, 4м3, грузовых мест 4 - по инфо от Лены                                                 FOB- 108 000 рублей                                                                                                                                            EXW- 164 000рублей (из них 780 USD за условия EXW)  в зависимости от верного объема, количества мест, и веса- сумма может измениться                                                                         Фрахт рассчитан через порт Шеньжень (YANTIAN)                                                                                          3.    22А Bacton Hill Road Frаzet, Pennsylvania 19З55, USA -> РФ, МО, г. Красногорск, д. 15 300кг, 1м3, 1 место На условиях EXW – 106 000 рублей, ставка включает:  – локальные расходы в порту отправки    - морской тариф до порта Saint Petersburg   - портовые сборы в порту прибытия Saint Petersburg   - авто вывоз до склада Красногорск ( отдельная авто газель)', E'Заинтересован');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Радка Рус ООО', E'Йортинген Германия Москва 90куб, 20 тонн паллеты, пласстмасса в гранулах. Растамаживаем в Смоленске', E'2020-03-10', E'2020-03-10', E'2600евро место погрузки: 47800 Uerdingen, район города Крефельд Германия', E'Условия поставки DAP, мы дали ставку на таможенную очистку груза. Пётр оформляет в Смоленске за 15000, пока возит 20-40т. в квартал. У нас дороже в 2р. ');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('дизайнер', E'Бразилия Москва', E'2020-03-10', E'2020-03-16', E'4000 АВИА без таможни', E'Контакт налажен. Взяли паузу из за доллара и короновируса');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Дёке Экстружн', E'Германия 95 кв 1 паллета, 1 тонна , голицыно свх, Москва выгрузка', E'2020-03-11', E'2020-03-11', E'570 евро доставка в сборной авто до СВХ Голицино+ 9000р автовывоз  в пределах МКАД.  транзитное время 10- 13 дней', E'Мы возим по ставке 250-300 евро.');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('prichal-int.ru', E'отправляю Вам технические характеристики одной средней поставки. Прошу рассчитать 2 варианта. ЭКСПОРТ. Россия Подольск-Барселона.   1 вариант.  10 шт понтонных платформ. Размеры:  1 ед 6000х2000х400мм. Вес 1 единицы: 450кг.  10 шт якорей с такелажем 880х500х580мм. Вес 1 комплекта 600кг. штабелирование Общая стоимость для клиента: 2 054 000 р.  2 вариант: 12 шт понтонных платформ. Размеры: 6000х2000х400мм. Вес 1 единицы: 450кг.  штабелирование Общая стоимость для клиента: 2 304 000 р.  Якорь это железобетон. Такелаж для якоря металлическая цепь. Понтонная платформа состоит из настила из сосны, металлической рамы с покрытием и модулей плавучести из полиэтилена низкого давления.  Сколько будут стоить ваши услуги по доставке такого груза в Испанию, растаможку и передачу клиенту?', E'2020-03-16', E'2020-03-16', E'3400 евро - автомашина тент 90м3', null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK', E'АЛБИСЕТЕ (ИСПАНИЯ) - КИРОВ 17 европаллет высота 130-140 см, 5 т, печи, камины, котлы. 4138 до 5 т С завода до склада "под ключ" с таможней. Оформляем на ERMAK они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK', E'АЛБИСЕТЕ (ИСПАНИЯ) - КИРОВ  авто 82 куб, С завода до склада "под ключ" с таможней  печи, камины, котлы.Оформляем на ERMAK они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK', E'КАУНАС(ЛИТВА) - КИРОВ 15 паллет,  печи, камины, котлы. С завода до склада "под ключ" с таможней. Оформляем на ERMAK они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK -экспорт', E'40 фут. контейнер, Россия Киров - Австралия (юго-запад)  Оформляем на ERMAK они участники ВЭД печи, камины, котлы. Транспорт и таможня  они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK -экспорт', E'40 фут. контейнер, Россия Киров - Япония (Токио Осако)  Оформляем на ERMAK они участники ВЭД печи, камины, котлы.  Транспорт и таможня  они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK -экспорт', E'40 фут контейнер. Оформляем на ERMAK они участники ВЭД,  Россия Киров - Чили печи, камины, котлы.  Транспорт и таможня  они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK -экспорт', E'40 фут контейнер. Оформляем на ERMAK они участники ВЭД, Россия Киров - Бразилия печи, камины, котлы.  Транспорт и таможня  они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK -экспорт', E'40 фут контейнер. Оформляем на ERMAK они участники ВЭД, РФ Киров - Того  печи, камины, котлы.  Транспорт и таможня  они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('ERMAK -экспорт', E'40 фут контейнер. Оформляем на ERMAK они участники ВЭД, РФ Киров - Америка (Штат Флорида, г. Орландо) печи, камины, котлы.  Транспорт и таможня  они участники ВЭД', E'2020-03-16', null, null, null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Vevux. красные крыши', E'Информация по рассчёту в почте', E'2020-03-13', E'2020-03-16', E'расчет под наш контракт, 17710 евро - ставка включает (там.платежи+там.сборы+транспорт (84163 Marklkofen Германия-Тверь-Москва)+ТЭО+коммерческая часть)', null);
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Potbruk', E'Пошльша Люблин - Москва Таможенная очистка Минск, 90 куб 21 тонна , тент, паллет, бок загрузка', E'2020-03-13', E'2020-03-13', E'1800 евро', E'Информацию проанализируют');
INSERT INTO potential_client_requests (company_name, info_for_estimation, date_of_request, date_of_answer, answer, notes)
values('Potbruk', E'Пошльша Любли - Минск  Таможенная очистка  Минск, 90 куб 21 тонна , тент, паллет, бок загрузка', E'2020-03-13', E'2020-03-13', E'1100 евро', E'Информацию проанализируют');